#!/bin/sh
#
# chkconfig: - 85 15
# description: MMonit server daemon
#

### BEGIN INIT INFO
# Provides: mmonit
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start:
# Default-Stop: 0 1 2 3 4 5 6
# Short-Description: Start and stop MMonit server
# Description: MMonit server daemon
### END INIT INFO

DESC="mmonit"
NAME=mmonit
DAEMON={{ pillar['mmonit-prefix'] }}/{{ pillar['mmonit-version'] }}/bin/$NAME
SCRIPTNAME=/etc/init.d/$NAME
PIDFILE=/var/run/mmonit.pid

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

d_start() {
        $DAEMON -p /var/run/ || echo -en "\n already running"
}

d_stop() {
        kill -QUIT `cat $PIDFILE` || echo -en "\n not running"
}

d_reload() {
        kill -HUP `cat $PIDFILE` || echo -en "\n can't reload"
}

case "$1" in
        start)
                echo -n "Starting $DESC: $NAME"
                d_start
                echo "."
                ;;
        stop)
                echo -n "Stopping $DESC: $NAME"
                d_stop
                echo "."
                ;;
        reload)
                echo -n "Reloading $DESC configuration..."
                d_reload
                echo "."
                ;;
        restart)
                echo -n "Restarting $DESC: $NAME"
                d_stop
                sleep 5
                d_start
                echo "."
                ;;
        *)
                echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
                exit 3
                ;;
esac

exit 0

